package magazinestore.entity;
// Generated 27-apr-2019 19.55.30 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "magazinestoredb", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
@NamedQueries({
	@NamedQuery(name = "Cliente.findAll", query = "SELECT c FROM Cliente c ORDER BY c.registerDate DESC"),
	@NamedQuery(name = "Cliente.findByEmail", query = "SELECT c FROM Cliente c WHERE c.email = :email"),
	@NamedQuery(name = "Cliente.countAll", query = "SELECT COUNT(c.email)FROM Cliente c"),
	@NamedQuery(name = "Cliente.checkLogin", query = "SELECT c FROM Cliente c WHERE c.email=:email AND c.password=:pass")
})
public class Cliente implements java.io.Serializable {

	private int clienteId;
	private String email;
	private String fullname;
	private String address;
	private String city;
	private String country;
	private String phone;
	private String zipcode;
	private String password;
	private Date registerDate;
	private Set<Recensione> recensiones = new HashSet<Recensione>(0);
	private Set<RivistaOrder> rivistaOrders = new HashSet<RivistaOrder>(0);

	public Cliente() {
	}

	public Cliente(int clienteId, String email, String fullname, String address, String city, String country,
			String phone, String zipcode, String password, Date registerDate) {
		this.clienteId = clienteId;
		this.email = email;
		this.fullname = fullname;
		this.address = address;
		this.city = city;
		this.country = country;
		this.phone = phone;
		this.zipcode = zipcode;
		this.password = password;
		this.registerDate = registerDate;
	}

	public Cliente(int clienteId, String email, String fullname, String address, String city, String country,
			String phone, String zipcode, String password, Date registerDate, Set<Recensione> recensiones,
			Set<RivistaOrder> rivistaOrders) {
		this.clienteId = clienteId;
		this.email = email;
		this.fullname = fullname;
		this.address = address;
		this.city = city;
		this.country = country;
		this.phone = phone;
		this.zipcode = zipcode;
		this.password = password;
		this.registerDate = registerDate;
		this.recensiones = recensiones;
		this.rivistaOrders = rivistaOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cliente_id", unique = true, nullable = false)
	public int getClienteId() {
		return this.clienteId;
	}

	public void setClienteId(int clienteId) {
		this.clienteId = clienteId;
	}

	@Column(name = "email", unique = true, nullable = false, length = 64)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fullname", nullable = false, length = 45)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "address", nullable = false, length = 128)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", nullable = false, length = 32)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", nullable = false, length = 64)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "zipcode", nullable = false, length = 24)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "password", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "register_date", nullable = false, length = 10)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Recensione> getRecensiones() {
		return this.recensiones;
	}

	public void setRecensiones(Set<Recensione> recensiones) {
		this.recensiones = recensiones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<RivistaOrder> getOrdineRevistas() {
		return this.rivistaOrders;
	}

	public void setOrdineRevistas(Set<RivistaOrder> rivistaOrders) {
		this.rivistaOrders = rivistaOrders;
	}

}
