package magazinestore.entity;
// Generated 27-apr-2019 19.55.30 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * DettagliOrdineId generated by hbm2java
 */
@Embeddable
public class DettagliOrdineId implements java.io.Serializable {
	
	private RivistaOrder rivistaOrder;
	private Rivista rivista;

	public DettagliOrdineId() {
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ordine_id", insertable = false, updatable = false,nullable = false)
	public RivistaOrder getRivistaOrder() {
		return this.rivistaOrder;
	}

	public void setRivistaOrder(RivistaOrder rivistaOrder) {
		this.rivistaOrder = rivistaOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rivista_id", insertable = false, updatable = false,nullable = false)
	public Rivista getRivista() {
		return this.rivista;
	}

	public void setRivista(Rivista rivista) {
		this.rivista = rivista;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rivistaOrder == null) ? 0 : rivistaOrder.hashCode());
		result = prime * result + ((rivista == null) ? 0 : rivista.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DettagliOrdineId other = (DettagliOrdineId) obj;
		if (rivistaOrder == null) {
			if (other.rivistaOrder != null)
				return false;
		} else if (!rivistaOrder.equals(other.rivistaOrder))
			return false;
		if (rivista == null) {
			if (other.rivista != null)
				return false;
		} else if (!rivista.equals(other.rivista))
			return false;
		return true;
	}
	


}
