package magazinestore.entity;
// Generated 27-apr-2019 19.55.30 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recensione generated by hbm2java
 */
@Entity
@Table(name = "recensione", catalog = "magazinestoredb")
public class Recensione implements java.io.Serializable {

	private Integer recensioneId;
	private Cliente cliente;
	private Rivista rivista;
	private int rating;
	private String headline;
	private String comment;
	private Date reviewTime;

	public Recensione() {
	}

	public Recensione(Cliente cliente, Rivista rivista, int rating, String headline, String comment, Date reviewTime) {
		this.cliente = cliente;
		this.rivista = rivista;
		this.rating = rating;
		this.headline = headline;
		this.comment = comment;
		this.reviewTime = reviewTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recensione_id", unique = true, nullable = false)
	public Integer getRecensioneId() {
		return this.recensioneId;
	}

	public void setRecensioneId(Integer recensioneId) {
		this.recensioneId = recensioneId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_id", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "revista_id", nullable = false)
	public Rivista getRivista() {
		return this.rivista;
	}

	public void setRivista(Rivista rivista) {
		this.rivista = rivista;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "headline", nullable = false, length = 128)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name = "comment", nullable = false, length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_time", nullable = false, length = 19)
	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}

}
